title: MATH 3610 (Intro to Math Modelling)
logo: /assets/img/sections-01-Gemini_Generated_Image_iq1bq9iq1bq9iq1b.jpeg
description: This is the material for when I (Julien Arino) am teaching the University of Manitoba MATH 3610 course on Introduction to Mathematical Modelling.
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
