#!/bin/bash

# Compile all slide files
for f in math-3610-*.Rnw
do
  # Remove concordance before sweaving
  # sed -i 's/concordance\=TRUE/concordance\=FALSE/g' $f
  # Now sweave
  R CMD Sweave --pdf $f
  #sed -i 's/\\SweaveOpts\{concordance\=FALSE\}//g' "${f%.tex}"
  #xelatex "${f%.tex}"
  #xelatex "${f%.tex}"
  #pdflatex "${f%.tex}"
  #pdflatex "${f%.tex}"  
  # Reactivate concordance
  #sed -i 's/concordance\=FALSE/concordance\=TRUE/g' $f
done

# Commit and push
git commit -a -m "Update slides"
git push
